"""Execution seam types for multi-backend steering.

A `Backend` owns identity, capability advertisement, and session creation; a `SteeringSession`
is the scope within which steering is in force and the unit of concurrency. The pipeline
interacts with backends through these two interfaces. Backend implementations live in
`steerability.backends`; this package holds every seam type and imports nothing from
`steerability.backends` at module level.
"""
from steerability.algorithms.core.execution.access import ModelAccess, PlannedFit, PlannedStep, SteerPlan
from steerability.algorithms.core.execution.backend import (
    Backend,
    SteeringSession,
    capabilities_for_spec,
    resolve_backend_class,
)
from steerability.algorithms.core.execution.contracts import (
    Alternative,
    BackendCapabilities,
    Capability,
    CaptureKinds,
    ConstraintKinds,
    InterventionKinds,
    ProcessorKinds,
    Requirements,
    SpecConstraint,
    SupportFailure,
    SupportReport,
    UnsupportedOperationError,
    UnsupportedPipelineError,
    any_of,
    evaluate_support,
    needs,
)
from steerability.algorithms.core.execution.fanout import (
    PartialBatchError,
    TransportError,
    derive_item_seed,
    run_bounded,
    with_transport_retries,
)
from steerability.algorithms.core.execution.params import GenerationParams, merge_lowered_params
from steerability.algorithms.core.execution.payloads import (
    Artifact,
    ArtifactProvenance,
    CaptureResult,
    CheckpointArtifact,
    ConstraintEntry,
    ConstraintSource,
    GenerationItem,
    HookEntry,
    InterventionEntry,
    InterventionSpec,
    ItemResult,
    LoRAArtifact,
    ModelArtifact,
    ModelFacts,
    OutputControlEntry,
    PreparedPrompt,
    ProcessorSpec,
    ProcessorSpecEntry,
    ScoringItem,
    StackEntry,
    StateControlEntry,
    as_constraint_source,
)
from steerability.algorithms.core.execution.spec import BackendSpec

__all__ = [
    "Artifact",
    "ArtifactProvenance",
    "Backend",
    "BackendCapabilities",
    "BackendSpec",
    "Capability",
    "CaptureKinds",
    "ConstraintEntry",
    "ConstraintKinds",
    "ConstraintSource",
    "as_constraint_source",
    "CaptureResult",
    "CheckpointArtifact",
    "GenerationItem",
    "GenerationParams",
    "HookEntry",
    "InterventionEntry",
    "InterventionKinds",
    "InterventionSpec",
    "ItemResult",
    "LoRAArtifact",
    "ModelAccess",
    "ModelArtifact",
    "ModelFacts",
    "OutputControlEntry",
    "PlannedFit",
    "PlannedStep",
    "PreparedPrompt",
    "ProcessorKinds",
    "ProcessorSpec",
    "ProcessorSpecEntry",
    "Requirements",
    "Alternative",
    "ScoringItem",
    "SpecConstraint",
    "StackEntry",
    "StateControlEntry",
    "SteerPlan",
    "SteeringSession",
    "SupportFailure",
    "SupportReport",
    "UnsupportedOperationError",
    "UnsupportedPipelineError",
    "PartialBatchError",
    "TransportError",
    "any_of",
    "capabilities_for_spec",
    "derive_item_seed",
    "evaluate_support",
    "merge_lowered_params",
    "needs",
    "resolve_backend_class",
    "run_bounded",
    "with_transport_retries",
]
